### ISSUE TITLE
Do not advise users to disable SELinux

### ISSUE THREAD

**Issue by alexhaydock** [hkparker/i2p-docker#19]
Thank you for your work on this useful container.

In your README for this repo, you suggest that users disable SELinux using the `setenforce 0` command, and manually change SELinux contexts using `chcon`.

This is unnecessary and (in the case of disabling SELinux) opens users up to risk.

Docker bind mounts have an inbuilt mechanism for automatically setting SELinux contexts on bind mounted directories.

In the case of this container, `:Z` could be added to the bind mount to make the recommendations from the README file unnecessary:
```
-v ~/.i2p:/var/lib/i2p:Z
```

As [noted by the Docker documentation](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label), using `:Z` will automatically set SELinux labels for the mount directory that allow it to be used just with the container in question.

(The lowercase `:z` can also be used for situations where the directory will be mounted and shared between multiple containers, but I don't see that as being necessary here.)

Thanks again for this project. :+1:

**Comment by hkparker** [comment]
Nice!  Thanks for pointing this out.  I'm not familiar with selinux and have been deferring to those more experienced for a solution here.  I'll add this to the README, unless you'd like to make a PR explaining this.

**Comment by hkparker** [comment]
@nevergone this work in your environment?

**Comment by hkparker** [comment]
Updated in 6ed46f18
