### ISSUE TITLE
I2p docker

### ISSUE THREAD

**Issue by jheszkn** [hkparker/i2p-docker#22]

**Comment by hkparker** [comment]
Is there an issue you meant to open here?

**Comment by jheszkn** [comment]
I have not problem, sorry.

**Comment by jheszkn** [comment]
![image](https://user-images.githubusercontent.com/64663771/80972868-ecba0b00-8e1e-11ea-8afe-56cd534ca6e1.png)

**Comment by jheszkn** [comment]
![image](https://user-images.githubusercontent.com/64663771/80972995-15420500-8e1f-11ea-9587-519424a28034.png)
